services:
  mongo:
    image: mongo:6
    container_name: school_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: school_backend
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/school
      - PORT=5000
      - NODE_ENV=production
    ports:
      - "5050:5000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BASE_URL: http://localhost:5050
    container_name: school_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:


